Create Contact Form - Portfolio Project
ouasamine/trials-portfolio pull request #1
Opened 2023-02-09 17:37 UTC by ouasamine

## Overview 
In this PR I created a contact form (Mobile Version) following the provided Figma template

## Implemented features
- Ability to send email messages using the contact form

2023-02-10 18:35 UTC, abdallahmalima requested changes
Hi @ouasamine , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Flexbox is used ✔
- Fields are wrapped in a single `form` element✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 18:35 UTC, abdallahmalima commented on index.html
> +        <form id="contact-form" action="https://formspree.io/">
- [ ] Please🙏 add some styling to make the your form match the  Figma design.
    ##   Your design
![image](https://user-images.githubusercontent.com/63445083/218164303-199048a2-0466-483b-b28b-9d73eca72ed5.png)

   ## Figma design
![image](https://user-images.githubusercontent.com/63445083/218165722-6ba7500d-967f-46e7-bf2c-a76c32af8186.png)

2023-02-10 18:35 UTC, abdallahmalima commented on index.html
> +          <button class="card-button" name="button" type="submit">Get in touch</button>
- [ ] Kindly🙋‍♀️ implement the button interactions, such as hover, active (when pressed), disabled, and enabled (default state), as shown in the Figma template. This will make the button more interactive for users👩‍🦳.
## Figma template
![image](https://user-images.githubusercontent.com/63445083/218168651-94e04781-41de-4b7e-8356-288fecfdd401.png)

2023-02-11 12:07 UTC, joel-kalema requested changes
### Hello @ouasamine 
Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne:
- Your form is  responsive :heavy_check_mark:
# Required Changes ♻️

- [ ] Check the comments under the review.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2023-02-13 16:05 UTC, closed without merging